import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import crypto from 'node:crypto'
import {START_META,CAMPAIGNS,PEOPLE,UNITS,ITEMS,TECHS,AGE1_TECH_IDS,AGE1_PEOPLE_IDS,AGE1_ARTIFACT_IDS,unitStatsAtLevel} from '../src/data.js'
import {createRun,battleIncome,objectiveResult,rewardOptions,applyReward,reinforcementHeal,reinforcementMultiplier,recoveryRate} from '../src/game/battleRules.js'
import {createEncounter,stepEncounter,unitStats,formationPositions,blockedGroundPoint,terrainFor} from '../src/game/combat.js'
import {claimAchievement,settleRun,migrateProgression,unitAvailable,reconcileUnits,startingCapacity,equipArtifact,equippedCount,availableCopies,packSpec,drawPack,addPackRewards,purchasePack,artifactSupply,itemEligibleForUnit,upgradePerson,evolveArtifact,trainUnit,buySupply,researchTech,supplyPrice} from '../src/game/progression.js'
import {rng,path,fight,simulateRun} from '../scripts/balance.mjs'
const fresh=()=>structuredClone(START_META)
const runFor=m=>createRun(m,'dawn',m.loadout,['warrior','slinger'],startingCapacity(m),m.discoveredUnits.filter(id=>unitAvailable(m,id)))
function unlock(m,n){settleRun(m,{campaign:'dawn',cleared:n,bestReached:n+1,gold:0,xp:0,tp:0});return m}
test('fresh save has only the two starter units and no equipped power',()=>{const m=fresh();assert.deepEqual(m.discoveredUnits,['warrior','slinger']);assert.equal(m.xp,0);assert.deepEqual(m.inventory,{});assert.equal(unitAvailable(m,'archer'),false);assert.equal(startingCapacity(m),2)})
test('research and People unlock from wins, not entering an uncleared battle',()=>{const m=unlock(fresh(),1);assert.equal(m.featureUnlocks.technology,false);unlock(m,2);assert.equal(m.featureUnlocks.technology,true);assert.equal(m.tp,2);assert.deepEqual(m.ownedTech,['fire']);unlock(m,4);assert.equal(m.featureUnlocks.people,false);unlock(m,5);assert.equal(m.characterCopies.elder,1);assert.equal(m.characterCopies.veteran,1);unlock(m,5);assert.equal(m.characterCopies.elder,1)})
test('research requires TP, prereqs and Age I eligibility; unlocked units require selected technology',()=>{const m=unlock(fresh(),2);assert.equal(researchTech(m,'irrigation'),false);assert.equal(researchTech(m,'archery'),true);assert.equal(researchTech(m,'archery'),false);assert.equal(unitAvailable(m,'archer'),false);m.loadout.tech=['archery'];assert.equal(unitAvailable(m,'archer'),true);m.tp=100;assert.equal(researchTech(m,'bronze'),false);assert.equal(researchTech(m,'agriculture'),true);m.loadout.tech=['agriculture'];assert.equal(startingCapacity(m),3)})
test('Hunter Bands unlock from battle three or their General; pending art units stay out of Age I',()=>{const m=unlock(fresh(),3);assert.equal(unitAvailable(m,'hunterBand'),true);m.discoveredUnits.push('warCart','bronzeGuard');assert.equal(unitAvailable(m,'warCart'),false);assert.equal(unitAvailable(m,'bronzeGuard'),false)})
test('signature level threshold is respected for future People',()=>{const m=unlock(fresh(),5);m.characterCopies.cleopatra=1;m.characterLevels.cleopatra=1;reconcileUnits(m);assert.equal(m.discoveredUnits.includes(PEOPLE.cleopatra.signatureUnit),false);m.characterLevels.cleopatra=5;reconcileUnits(m);assert.equal(m.discoveredUnits.includes(PEOPLE.cleopatra.signatureUnit),true)})
test('one copy equips to one unit type; a second copy can equip independently',()=>{const m=fresh();m.inventory.leatherLamellar=2;assert.equal(equipArtifact(m,'leatherLamellar','warrior'),true);assert.equal(equipArtifact(m,'leatherLamellar','slinger'),true);assert.equal(equippedCount(m,'leatherLamellar'),2);assert.equal(availableCopies(m,'leatherLamellar'),0);assert.equal(equipArtifact(m,'leatherLamellar','warrior'),false);assert.deepEqual(m.unitEquipment.warrior,['leatherLamellar'])})
test('replacing one slot returns its copy and preserves other units; incompatible gear is rejected',()=>{const m=fresh();Object.assign(m.inventory,{leatherLamellar:2,stoneAxeGrip:1,boneCharm:1,spearShaft:1});equipArtifact(m,'leatherLamellar','warrior');equipArtifact(m,'leatherLamellar','slinger');equipArtifact(m,'stoneAxeGrip','warrior');equipArtifact(m,'boneCharm','warrior');assert.equal(availableCopies(m,'leatherLamellar'),1);assert.deepEqual(m.unitEquipment.slinger,['leatherLamellar']);assert.equal(equipArtifact(m,'spearShaft','slinger'),false)})
test('artifact pools contain equipment usable by discovered, finished units',()=>{const m=fresh();assert.equal(artifactSupply(m).includes('spearShaft'),false);m.discoveredUnits.push('spear');assert.equal(artifactSupply(m).includes('spearShaft'),true);for(const id of artifactSupply(m))assert.ok(m.discoveredUnits.some(u=>itemEligibleForUnit(ITEMS[id],u)))})
test('duplicate pack reveals mark only the first new discovery; rarer packs guarantee Rare+',()=>{const m=unlock(fresh(),5),result=addPackRewards(m,{ids:['narmer','narmer'],bonus:8},'people');assert.deepEqual(result.map(x=>x.isNew),[true,false]);assert.equal(m.characterCopies.narmer,2);for(let seed=1;seed<=100;seed++){const p=drawPack(packSpec(m,'great'),rng(seed));assert.ok(p.ids.some(id=>['Rare','Epic','Legend'].includes(PEOPLE[id].rarity)));assert.ok(p.bonus>=8&&p.bonus<=16)}})
test('paid pack contents are banked atomically before the reveal animation or a reload',()=>{const m=fresh();m.gold=35;const spec=packSpec(m,'basic','artifact'),rewards=drawPack(spec,rng(1));assert.equal(purchasePack(m,spec,rewards).length,1);assert.equal(m.gold,0);assert.equal(m.inventory[rewards.ids[0]],1);assert.equal(purchasePack(m,spec,rewards),null);assert.equal(m.inventory[rewards.ids[0]],1);assert.equal(m.stats.packsOpened,1)})
test('achievement claims check current state and award only once',()=>{const m=fresh();assert.equal(claimAchievement(m,'win1'),false);m.stats.battlesWon=1;assert.equal(claimAchievement(m,'win1'),true);const gold=m.gold;assert.equal(claimAchievement(m,'win1'),false);assert.equal(m.gold,gold)})
test('training, supplies and evolution never spend unaffordable currency or consume collection thresholds',()=>{const m=fresh();assert.equal(trainUnit(m,'warrior'),false);assert.equal(buySupply(m,'leatherLamellar'),false);m.xp=10;assert.equal(trainUnit(m,'warrior'),true);assert.equal(m.xp,0);assert.ok(unitStatsAtLevel('warrior',2).health>=119);m.inventory.leatherLamellar=2;m.artifactLevels.leatherLamellar=1;m.gold=20;assert.equal(evolveArtifact(m,'leatherLamellar'),true);assert.equal(m.inventory.leatherLamellar,2);assert.equal(m.gold,0);assert.equal(evolveArtifact(m,'leatherLamellar'),false)})
test('People promotions use Age I costs and apply real combat/recovery/economy bonuses',()=>{const m=unlock(fresh(),5);m.characterCopies.elder=2;m.gold=55;assert.equal(upgradePerson(m,'elder'),true);assert.equal(m.gold,0);const base=runFor(fresh()),withPeople=runFor(m);assert.ok(unitStats('warrior',withPeople).damage>unitStats('warrior',base).damage);assert.ok(reinforcementMultiplier(withPeople)>reinforcementMultiplier(base));assert.ok(recoveryRate(withPeople)>recoveryRate(base));assert.ok(battleIncome(withPeople,CAMPAIGNS.dawn.stages[0],false).gold>battleIncome(base,CAMPAIGNS.dawn.stages[0],false).gold)})
test('all six Age I People have cumulative effects for each playable level',()=>{for(const id of AGE1_PEOPLE_IDS){assert.equal(PEOPLE[id].effects.length,PEOPLE[id].levels.length);for(const effect of PEOPLE[id].effects)assert.ok(Object.keys(effect).length)}const m=unlock(fresh(),5);m.loadout.leader='merchant';m.characterLevels.merchant=2;assert.equal(supplyPrice(m,100),92);m.loadout.leader='narmer';m.characterLevels.narmer=3;assert.ok(reinforcementHeal(runFor(m))>.18);m.loadout.general='sargon';m.characterLevels.sargon=4;const r=runFor(m),d=unitStats('warrior',r).attackSpeed;r.wins=10;assert.ok(unitStats('warrior',r).attackSpeed>d)})
test('every Age I artifact increases a stated combat statistic on a compatible unit',()=>{for(const id of AGE1_ARTIFACT_IDS){const unit=Object.keys(UNITS).find(u=>UNITS[u].ageId==='origins'&&itemEligibleForUnit(ITEMS[id],u));assert.ok(unit,id);const r=runFor(fresh()),a=unitStats(unit,r);r.unitEquipment={[unit]:[id]};r.artifactLevels={[id]:1};const b=unitStats(unit,r);assert.ok(['health','damage','attackSpeed','armor'].some(k=>b[k]>a[k]),id)}})
test('Wheel and Writing give their advertised Age I effects',()=>{const r=runFor(fresh()),a=unitStats('warrior',r),income=battleIncome(r,CAMPAIGNS.dawn.stages[2],false);r.tech=['wheel','writing'];assert.ok(unitStats('warrior',r).moveSpeed>a.moveSpeed);assert.ok(battleIncome(r,CAMPAIGNS.dawn.stages[2],false).xp>income.xp)})
test('fixed enemies do not scale with the player; finale has a stronger guard',()=>{const m=fresh(),r=runFor(m),stage=CAMPAIGNS.dawn.stages[14],a=createEncounter(r,stage,undefined,rng(1));r.unitLevels={warrior:50,slinger:50};const b=createEncounter(r,stage,undefined,rng(1));assert.deepEqual(a.enemy,b.enemy);assert.ok(a.enemy[0].maxHp>UNITS.warrior.health*stage.mult);assert.ok(a.enemy[0].stats.damage>unitStats('warrior',r,'enemy',stage.mult).damage)})
test('timeouts settle once, objectives have explicit boundaries, and dead armies cannot earn preservation',()=>{const r=runFor(fresh()),stage=CAMPAIGNS.dawn.stages[0],b=createEncounter(r,stage);b.time=179.99;stepEncounter(b,r,stage,0,.04);assert.equal(b.done,true);assert.equal(b.victory,false);assert.equal(b.timedOut,true);const time=b.time;stepEncounter(b,r,stage,0,.04);assert.equal(b.time,time);const tempo=CAMPAIGNS.dawn.stages[2];b.time=tempo.objective.parSeconds;assert.equal(objectiveResult(tempo,b),true);b.time+=.01;assert.equal(objectiveResult(tempo,b),false);b.player[0].dead=true;assert.equal(objectiveResult(stage,b),false)})
test('temporary upgrades cap and recruitment cannot exceed capacity',()=>{let r=runFor(fresh());for(let i=0;i<200;i++){const choices=rewardOptions(r,rng(i+1));if(!choices.length)break;r=applyReward(r,choices.find(c=>c.kind==='upgrade')||choices[0])}assert.ok(r.upgrades.damage<=1.80);assert.ok(r.upgrades.armorBonus<=15);r=applyReward(r,{kind:'unit',id:'warrior'});assert.equal(r.roster.length,r.deployCap)})
test('first-clear and star rewards cannot be farmed; campaign unlock is preserved',()=>{const m=fresh(),info={campaign:'dawn',victory:true,cleared:15,bestReached:15,gold:100,xp:50,tp:5,stars:3};settleRun(m,info);assert.equal(m.gold,225);assert.equal(m.xp,80);assert.ok(m.unlockedCampaigns.includes('firstcities'));const before=m.gold;settleRun(m,info);assert.equal(m.gold-before,100);assert.equal(m.stats.campaignsCompleted,1)})
test('legacy migration preserves owned progression and corrects reached-versus-cleared records once',()=>{const m=fresh();m.gold=999;m.inventory.boneCharm=4;m.campaignStats.dawn={best:6,stars:0};m.ownedTech=['archery'];migrateProgression(m);assert.equal(m.gold,999);assert.equal(m.inventory.boneCharm,4);assert.equal(m.campaignStats.dawn.cleared,5);assert.ok(m.discoveredUnits.includes('hunterBand'));assert.deepEqual(m.ownedTech,['archery','fire']);const tp=m.tp;migrateProgression(m);assert.equal(m.tp,tp)})
test('all 15 encounters have reachable deployments, objectives, rewards and terrain; mature formation wins every encounter',()=>{const m=unlock(fresh(),5);m.loadout.tech=['agriculture','archery','copper'];m.ownedTech=[...AGE1_TECH_IDS];reconcileUnits(m);for(const id of m.discoveredUnits)m.unitLevels[id]=9;m.unitEquipment={spear:['leatherLamellar','spearShaft'],archer:['leatherLamellar','edgedProjectiles']};m.artifactLevels={leatherLamellar:3,spearShaft:3,edgedProjectiles:3};const r=createRun(m,'dawn',m.loadout,['spear','archer','spear','archer','archer'],5,['spear','archer']);assert.equal(CAMPAIGNS.dawn.stages.length,15);for(const [i,stage] of CAMPAIGNS.dawn.stages.entries()){assert.ok(stage.gold>0&&stage.xp>0&&stage.objective);const terrain=terrainFor(stage);for(const p of createEncounter(r,stage).enemy)assert.equal(blockedGroundPoint(p.x,p.y,terrain),false,stage.name);const capacity=i<5?3:i<10?4:5,encounter={...r,roster:r.roster.slice(0,capacity),deployCap:capacity};const {b}=fight(encounter,stage,i,'skilled',rng(i+1));assert.equal(b.victory,true,stage.name);assert.ok(b.time<stage.timeLimit);assert.equal(objectiveResult(stage,b),true,stage.name+' optional objective');}})
test('seeded fresh-save progression is reproducible and first-run completion is blocked by battle strength',()=>{const a=path('average',2),b=path('average',2);assert.deepEqual(a,b);assert.ok(a.runs[0].bestReached>=3&&a.runs[0].bestReached<=5);assert.equal(a.runs[0].victory,false);assert.ok(a.runs[0].bank.gold>=60);assert.ok(a.runs[3].bestReached>=14)})
test('every legal starter composition wins the opening encounters but cannot conquer on its first run',()=>{for(const first of ['warrior','slinger'])for(const second of ['warrior','slinger'])for(const skill of ['average','skilled']){const r=simulateRun(fresh(),skill,rng(7),[first,second]);assert.ok(r.cleared>=2);assert.equal(r.victory,false)}})
test('all fourteen future campaigns retain their complete encounter data',()=>{const future=Object.fromEntries(Object.entries(CAMPAIGNS).filter(([id])=>id!=='dawn')),digest=crypto.createHash('sha256').update(JSON.stringify(future)).digest('hex');assert.equal(digest,fs.readFileSync('docs/pass4/future-encounters.sha256','utf8').trim())})
